name: 🐛 Bug Report
description: Report a bug in Wealth Vault
title: "[Bug]: "
labels: ["bug"]

body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear description of the bug
      placeholder: Describe what went wrong...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What should have happened?
      placeholder: I expected...
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Browser, OS, device info
      placeholder: "Chrome on Windows 11"

  - type: textarea
    id: additional
    attributes:
      label: Screenshots or additional info
      description: Add any other helpful details
      placeholder: You can drag and drop images here...
