/**
 * TaxAnalytics Utility (#482)
 * Provides mathematical helpers for calculating tax alpha and harvest efficacy.
 */
class TaxAnalytics {
    /**
     * Calculates the "Tax Alpha" or total savings generated by a harvest.
     * @param {number} realizedLoss - Total loss realized in USD.
     * @param {number} shortTermRate - Marginal tax rate for short-term gains (0 to 1).
     * @param {number} longTermRate - Marginal tax rate for long-term gains (0 to 1).
     * @param {boolean} isShortTerm - Whether the lot was held < 1 year.
     */
    calculateSavings(realizedLoss, shortTermRate = 0.35, longTermRate = 0.15, isShortTerm = true) {
        const rate = isShortTerm ? shortTermRate : longTermRate;
        return Math.abs(realizedLoss) * rate;
    }

    /**
     * Determines if a harvest is "Efficacious" after considering bid-ask spreads and trading commissions.
     * @param {number} grossLoss - Total paper loss.
     * @param {number} tradingCosts - Total cost of buy + sell of proxy.
     * @param {number} taxRate - Expected tax avoidance rate.
     */
    isEfficacious(grossLoss, tradingCosts, taxRate) {
        const taxBenefit = Math.abs(grossLoss) * taxRate;
        return taxBenefit > (tradingCosts * 1.5); // Ensure benefit exceeds costs by 50% buffer
    }

    /**
     * Checks for "Substantially Identical" ticker matches.
     * In a production app, this would use a database of security types/CUSIPs.
     */
    areAssetsSubstantiallyIdentical(symbolA, symbolB) {
        if (symbolA === symbolB) return true;

        // Mock mapping of identical ETFs (e.g., SPY and VOO are nearly identical)
        const identicalPairs = [
            ['SPY', 'VOO'],
            ['VTI', 'ITOT'],
            ['QQQ', 'VGT']
        ];

        return identicalPairs.some(pair =>
            (pair.includes(symbolA) && pair.includes(symbolB))
        );
    }
}

export default new TaxAnalytics();
